# Generated by Django 5.2.17 on 2026-09-23 02:38

import django.db.models.deletion
import locations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[locations.models.validate_latitude])),
                ('longitude', models.FloatField(validators=[locations.models.validate_longitude])),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('marker_type', models.CharField(choices=[('meeting_point', 'Meeting Point'), ('danger', 'Danger'), ('food', 'Food'), ('parking', 'Parking'), ('important', 'Important'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('latitude', models.FloatField(validators=[locations.models.validate_latitude])),
                ('longitude', models.FloatField(validators=[locations.models.validate_longitude])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_markers', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room'], name='locations_m_room_id_68206b_idx')],
            },
        ),
    ]
